--
-- V1 - baseline schema.
--
-- Captured from the live namma_journey database with pg_dump --schema-only. Until now the
-- schema came from Hibernate ddl-auto=update plus a pile of hand-run .sql scripts in the
-- repository root, so no environment could be rebuilt from source with any confidence.
-- This file is that schema written down once, so Flyway can own it from here on.
--
-- Adoption on an existing database: Flyway is configured with baseline-on-migrate and
-- baseline-version 1, so a populated schema with no history table is stamped as already at
-- V1 and this file is NOT replayed. A fresh, empty database runs it normally.
--
-- Add changes as new V2__*.sql, V3__*.sql files. Never edit this one once it has been
-- applied anywhere - Flyway validates its checksum.
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;


--
-- Name: drivers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drivers (
    id bigint NOT NULL,
    aadhaar_number character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    license_number character varying(255) NOT NULL,
    mobile character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    aadhaar_photo character varying(1000),
    email character varying(255),
    license_photo character varying(1000),
    photo character varying(1000),
    first_login boolean DEFAULT true NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    CONSTRAINT drivers_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);



--
-- Name: drivers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.drivers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.drivers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id uuid NOT NULL,
    booking_id character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(500) NOT NULL,
    read boolean NOT NULL,
    recipient_id character varying(255) NOT NULL,
    recipient_role character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL
);



--
-- Name: otps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otps (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    expiry_time timestamp(6) without time zone NOT NULL,
    otp character varying(6) NOT NULL,
    verified boolean NOT NULL
);



--
-- Name: otps_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.otps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Name: owners; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.owners (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);



--
-- Name: owners_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.owners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.owners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Name: package_bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.package_bookings (
    id uuid NOT NULL,
    booking_date timestamp(6) without time zone NOT NULL,
    cancellation_reason character varying(255),
    cancelled_at timestamp(6) without time zone,
    confirmed_at timestamp(6) without time zone,
    duration_days integer,
    duration_nights integer,
    number_of_persons integer NOT NULL,
    package_category character varying(255),
    package_id bigint NOT NULL,
    package_name character varying(255) NOT NULL,
    price_per_person double precision,
    special_requests character varying(255),
    status character varying(255) NOT NULL,
    total_amount double precision NOT NULL,
    travel_date date NOT NULL,
    user_email character varying(255) NOT NULL,
    user_id uuid NOT NULL,
    user_name character varying(255) NOT NULL,
    user_phone character varying(255) NOT NULL,
    CONSTRAINT package_bookings_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying])::text[])))
);



--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id uuid NOT NULL,
    amount double precision NOT NULL,
    booking_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    driver_id bigint,
    payment_date timestamp(6) without time zone,
    payment_method character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    upi_transaction_id character varying(255),
    user_id uuid NOT NULL,
    verified_date timestamp(6) without time zone,
    upi_link_expires_at timestamp(6) without time zone,
    CONSTRAINT payments_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['UPI'::character varying, 'CASH'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'FAILED'::character varying])::text[])))
);



--
-- Name: pricing_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pricing_config (
    id bigint NOT NULL,
    price_per_km double precision NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by bigint NOT NULL,
    price_per_hour double precision
);



--
-- Name: pricing_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pricing_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pricing_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id uuid NOT NULL,
    booking_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    driver_id bigint NOT NULL,
    driver_name character varying(255) NOT NULL,
    feedback character varying(1000),
    rating integer NOT NULL,
    user_id uuid NOT NULL,
    user_name character varying(255) NOT NULL
);



--
-- Name: travel_bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.travel_bookings (
    id uuid NOT NULL,
    booking_date timestamp(6) without time zone NOT NULL,
    distance_km double precision NOT NULL,
    estimated_time_minutes bigint NOT NULL,
    from_place character varying(255) NOT NULL,
    route_details text,
    status character varying(255) NOT NULL,
    to_place character varying(255) NOT NULL,
    travel_days integer NOT NULL,
    user_id uuid NOT NULL,
    user_name character varying(255) NOT NULL,
    user_phone character varying(255) NOT NULL,
    ac_type character varying(255) NOT NULL,
    from_date date NOT NULL,
    to_date date NOT NULL,
    travel_members integer NOT NULL,
    driver_id bigint,
    total_amount double precision DEFAULT 0 NOT NULL,
    from_lat double precision,
    from_lon double precision,
    to_lat double precision,
    to_lon double precision,
    booking_hours integer,
    price_per_hour_at_booking double precision,
    booking_type character varying(255) DEFAULT 'DISTANCE_BASED'::character varying NOT NULL,
    version bigint,
    CONSTRAINT travel_bookings_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'STARTED'::character varying, 'COMPLETED'::character varying, 'ENDED'::character varying, 'CANCELLED'::character varying])::text[])))
);



--
-- Name: travel_packages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.travel_packages (
    id bigint NOT NULL,
    accommodation_details character varying(255),
    accommodation_included boolean NOT NULL,
    active boolean NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    description text,
    duration_days integer NOT NULL,
    duration_nights integer NOT NULL,
    food_details character varying(255),
    food_included boolean NOT NULL,
    guide_included boolean NOT NULL,
    highlights text,
    image_url character varying(255),
    itinerary text,
    max_group_size integer NOT NULL,
    name character varying(255) NOT NULL,
    places_included text NOT NULL,
    price_per_person double precision NOT NULL,
    sightseeing_included boolean NOT NULL,
    state character varying(255) NOT NULL,
    toll_free boolean NOT NULL,
    transport_details character varying(255),
    transport_included boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT travel_packages_category_check CHECK (((category)::text = ANY ((ARRAY['TEMPLE'::character varying, 'HONEYMOON'::character varying, 'ADVENTURE'::character varying, 'HILL_STATION'::character varying, 'BEACH'::character varying, 'HERITAGE'::character varying, 'WILDLIFE'::character varying, 'PILGRIMAGE'::character varying, 'FAMILY'::character varying, 'STATE_SPECIAL'::character varying])::text[])))
);



--
-- Name: travel_packages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.travel_packages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.travel_packages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Name: trip_driver_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trip_driver_photos (
    id uuid NOT NULL,
    booking_id uuid NOT NULL,
    captured_at timestamp(6) without time zone NOT NULL,
    driver_id bigint NOT NULL,
    photo_path character varying(2000) NOT NULL
);



--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    login_type character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255),
    role character varying(255) NOT NULL,
    password character varying(255),
    CONSTRAINT users_login_type_check CHECK (((login_type)::text = ANY ((ARRAY['GOOGLE'::character varying, 'PHONE'::character varying, 'EMAIL'::character varying])::text[])))
);



--
-- Name: drivers drivers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);



--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);



--
-- Name: otps otps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otps
    ADD CONSTRAINT otps_pkey PRIMARY KEY (id);



--
-- Name: owners owners_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.owners
    ADD CONSTRAINT owners_pkey PRIMARY KEY (id);



--
-- Name: package_bookings package_bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.package_bookings
    ADD CONSTRAINT package_bookings_pkey PRIMARY KEY (id);



--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);



--
-- Name: pricing_config pricing_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pricing_config
    ADD CONSTRAINT pricing_config_pkey PRIMARY KEY (id);



--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);



--
-- Name: travel_bookings travel_bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_bookings
    ADD CONSTRAINT travel_bookings_pkey PRIMARY KEY (id);



--
-- Name: travel_packages travel_packages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_packages
    ADD CONSTRAINT travel_packages_pkey PRIMARY KEY (id);



--
-- Name: trip_driver_photos trip_driver_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trip_driver_photos
    ADD CONSTRAINT trip_driver_photos_pkey PRIMARY KEY (id);



--
-- Name: drivers uk34x3gwter5i46jdm3tjmw7jp3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT uk34x3gwter5i46jdm3tjmw7jp3 UNIQUE (aadhaar_number);



--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);



--
-- Name: drivers ukcr60ij36fuvtcb87298g6rct6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT ukcr60ij36fuvtcb87298g6rct6 UNIQUE (license_number);



--
-- Name: users ukdu5v5sr43g5bfnji4vb8hg5s3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);



--
-- Name: owners ukdw1w2xj1axp1le5oionrjfk7t; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.owners
    ADD CONSTRAINT ukdw1w2xj1axp1le5oionrjfk7t UNIQUE (email);



--
-- Name: drivers ukluxf5vgalaid2fl9dw2u7hdtw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT ukluxf5vgalaid2fl9dw2u7hdtw UNIQUE (mobile);



--
-- Name: drivers ukre66mdta4hy6pxm2w1rqu08jv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT ukre66mdta4hy6pxm2w1rqu08jv UNIQUE (email);



--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);



--
-- PostgreSQL database dump complete
--
